# This is a basic workflow to help you get started with Actions

name: Build & Deploy Packer Template
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the packer template and deploy to AWS
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    #   uses: hashicorp/packer-github-actions@master
    #   with:
    #     command: build
    #     arguments: "-color=false -on-error=abort"
    #     target: packer/new-aws-ubuntu.pkr.hcl
    #     working_directory: ${{ github.workspace }}
      env: # Grab the AWS environment variables for deployment
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Use latest Packer
      uses: hashicorp-contrib/setup-packer@v2
      with:
          packer-version: 1.8.3

    - name: Build image from template
      working-directory: ${{ github.workspace }}
      run: zip webappDEV.zip ./* && ls -a && cd ami_packer && packer init ami.pkr.hcl && packer build ami.pkr.hcl

